// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhanhVn.EntityFramework;
using NhanhVn.EntityFramework.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NhanhVn.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230212100518_RemovePrediscountColumn")]
    partial class RemovePrediscountColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NhanhVn.EntityFramework.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CalcTotalMoney")
                        .HasColumnType("double precision")
                        .HasColumnName("calctotalmoney");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("integer")
                        .HasColumnName("carrierid");

                    b.Property<string>("CarrierName")
                        .HasColumnType("text")
                        .HasColumnName("carriername");

                    b.Property<int>("CodFee")
                        .HasColumnType("integer")
                        .HasColumnName("codfee");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<string>("CustomerCity")
                        .HasColumnType("text")
                        .HasColumnName("customercity");

                    b.Property<int?>("CustomerCityId")
                        .HasColumnType("integer")
                        .HasColumnName("customercityid");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<string>("CustomerMobile")
                        .HasColumnType("text")
                        .HasColumnName("customermobile");

                    b.Property<int>("CustomerShipFee")
                        .HasColumnType("integer")
                        .HasColumnName("customershipfee");

                    b.Property<int>("DeclaredFee")
                        .HasColumnType("integer")
                        .HasColumnName("declaredfee");

                    b.Property<string>("DeliveryDate")
                        .HasColumnType("text")
                        .HasColumnName("deliverydate");

                    b.Property<int?>("DepotId")
                        .HasColumnType("integer")
                        .HasColumnName("depotid");

                    b.Property<string>("DepotName")
                        .HasColumnType("text")
                        .HasColumnName("depotname");

                    b.Property<string>("MerchantTrackingNumber")
                        .HasColumnType("text")
                        .HasColumnName("merchanttrackingnumber");

                    b.Property<double>("MoneyDeposit")
                        .HasColumnType("double precision")
                        .HasColumnName("moneydeposit");

                    b.Property<double>("MoneyDiscount")
                        .HasColumnType("double precision")
                        .HasColumnName("moneydiscount");

                    b.Property<double>("MoneyTransfer")
                        .HasColumnType("double precision")
                        .HasColumnName("moneytransfer");

                    b.Property<int>("NhanhId")
                        .HasColumnType("integer")
                        .HasColumnName("nhanhid");

                    b.Property<int>("OverWeightShipFee")
                        .HasColumnType("integer")
                        .HasColumnName("overweightshipfee");

                    b.Property<List<OrderProduct>>("Products")
                        .HasColumnType("jsonb")
                        .HasColumnName("products");

                    b.Property<int>("ReturnFee")
                        .HasColumnType("integer")
                        .HasColumnName("returnfee");

                    b.Property<string>("SaleChannel")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("salechannel");

                    b.Property<int>("ShipFee")
                        .HasColumnType("integer")
                        .HasColumnName("shipfee");

                    b.Property<string>("StatusCode")
                        .HasColumnType("text")
                        .HasColumnName("statuscode");

                    b.Property<string>("StatusName")
                        .HasColumnType("text")
                        .HasColumnName("statusname");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("typeid");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("NhanhVn.EntityFramework.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AvgCost")
                        .HasColumnType("double precision")
                        .HasColumnName("avgcost");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("categoryid");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("CreatedDateTime")
                        .HasColumnType("text")
                        .HasColumnName("createddatetime");

                    b.Property<string>("IdNhanh")
                        .HasColumnType("text")
                        .HasColumnName("idnhanh");

                    b.Property<string>("ImportPrice")
                        .HasColumnType("text")
                        .HasColumnName("importprice");

                    b.Property<ProductInventory>("Inventory")
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parentid");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TypeId")
                        .HasColumnType("text")
                        .HasColumnName("typeid");

                    b.Property<string>("TypeName")
                        .HasColumnType("text")
                        .HasColumnName("typename");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<double?>("Vat")
                        .HasColumnType("double precision")
                        .HasColumnName("vat");

                    b.Property<double?>("WholesalePrice")
                        .HasColumnType("double precision")
                        .HasColumnName("wholesaleprice");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
